### ISSUE TITLE
Does not work after changing the width and rolling back to 300px

### ISSUE THREAD

**Issue by gumbarros** [Uiniel/zen-mods#1]
![image](https://github.com/user-attachments/assets/f9d75487-f2f2-4163-aaab-1a0064737976)

**Comment by Uiniel** [comment]
Can confirm it happens sometimes when changing width. I think that's a zen bug, I have a screenshot of both the setting and about:config attached, which shows that sometimes letters are missing? As a workaround: changing it repeatedly sometimes fixes it (maybe rewriting the missing letters?). Changing it directly in about:config also works, but you have to restart your browser.

![image](https://github.com/user-attachments/assets/faa38c13-9bd7-4d50-8e9a-1be5b9c99901)
![image](https://github.com/user-attachments/assets/6898503f-ad60-424d-8920-eafce4e784f2)

**Comment by Uiniel** [comment]
I made a zen browser bug report zen-browser/desktop#3558

**Comment by Uiniel** [comment]
closing this since it seems to be a browser bug
