### ISSUE TITLE
Please fix the bugs

### ISSUE THREAD

**Issue by Artistic-Rik** [Uiniel/zen-mods#11]
Unexpected behavior 
1. When expanding the sidebar in Collapsed toolbar mode
![GUpGSsJ4Vg](https://github.com/user-attachments/assets/541de182-ca0f-4a65-8a06-078be4c96e8a)

2. Please expand the full sidebar in compact mode. Currently, the upper part of the sidebar is not expanding.

After installing:
![XKkxw2EEKj](https://github.com/user-attachments/assets/45556974-3b44-431c-8659-0727e59d62b4) 
Default: 
![P7tGnlG7TU](https://github.com/user-attachments/assets/3e536a47-7cb9-44b5-afc5-b6f750faa938)

4. Try to **remove** the _**Black Border**_ and make the corner **Rounded** like default.

**Comment by Roxiun** [comment]
Also is it possible not to have the different colour?

**Comment by Uiniel** [comment]
> Unexpected behavior
> 
>     1. When expanding the sidebar in Collapsed toolbar mode

Clicking the expand sidebar button changes the browser layout from collapsed toolbar to multiple toolbars, currently only collapsed toolbar is supported (#3 ).
