### ISSUE TITLE
no close icon in tab bar opened on hover

### ISSUE THREAD

**Issue by Darkmagister** [Uiniel/zen-mods#14]
i've the collapsed bar and you mod to have it open on hover, but there is no close icon anymore ... so to close i need to open the tab and crtl+w 
is it possible to have the close button while open ?

**Comment by Uiniel** [comment]
It's already fixed in the dev version and I'll update it in the theme store as soon as the other bugs are fixed. (If your mouse has a scroll wheel you can click with the middle mouse button on a tab in the meantime to close it)

**Comment by Darkmagister** [comment]
oh great and thanks for the workaround for now.
