### ISSUE TITLE
Mod broken in 1.02-b.2?

### ISSUE THREAD

**Issue by scoobydooxp** [Uiniel/zen-mods#17]
I upgraded to 1.02-b.2 this morning and the Sidebar Expand on Hover seems to expand behind the open browser window. If you click on an icon in the sidebar, the mod will expand the sidebar temporarily if a tab has to be reloaded because it unloaded.

Great mod, keep up the great work!

**Comment by Uiniel** [comment]
yeah I just created an issue for that (#16)

**Comment by scoobydooxp** [comment]
Missed it by minutes. Thank you!
