### ISSUE TITLE
Unusual behavior

### ISSUE THREAD

**Issue by RowanSkie** [Uiniel/zen-mods#2]
![image](https://github.com/user-attachments/assets/37600e48-52ca-46b2-ad54-1b510fe68410)

**Comment by Frederic-C** [comment]
yep, same here.
The panel is taking the expanded width when supposly compacted, only tab size is reduced / expanded on hover. The last zen update is surely a lot of changes under the hood!

**Comment by Uiniel** [comment]
Can you confirm that you are using the collapsed toolbar setting? That's currently the only supported one (since the others are a lot more work).

**Comment by RowanSkie** [comment]
On compacted mode, the expanded sidebar becomes transparent with a black border of the entire thing.

**Comment by Uiniel** [comment]
I was talking about this setting not compact mode. (Compact mode as well only works with a collapsed toolbar (and not perfectly))
![image](https://github.com/user-attachments/assets/849dd44a-ef22-4cad-b72a-4016fe49b9bf)

**Comment by RowanSkie** [comment]
Okay, now I see it. I wasn't using the Collapsed Toolbar, instead using Multiple Toolbars + Compact Mode.

**Comment by Uiniel** [comment]
#3
