### ISSUE TITLE
The button above the vertical tabs bar will move to the top of the vertical tabs bar.

### ISSUE THREAD

**Issue by emberrolland** [Uiniel/zen-mods#31]
On Zen 1.0.2-b.3 (Firefox 133.0.3).
If Siderbar Expand on Hover is disabled, the setting button is above the vertical tabs bar.
![图片](https://github.com/user-attachments/assets/feb6f350-e045-4d8a-ace7-21c414aa9781)
If Siderbar Expand on Hover is disabled, the setting button moves to the top of the vertical tabs bar.
![图片](https://github.com/user-attachments/assets/f8124a6c-eaf8-41e0-8d73-1477df4eab4a)

**Comment by Uiniel** [comment]
I know, changing that made a lot of stuff easier. You can move them up next to the back/forward buttons in customize toolbar to get them to the previous location.

**Comment by emberrolland** [comment]
If I move it up next to the back/forward buttons, then it will leave a space on the top of vertical tabs bar
![图片](https://github.com/user-attachments/assets/1af88554-2d08-4c46-8c3c-a69575b43255)

**Comment by Uiniel** [comment]
oh yeah sorry that's a known bug #23 will be fixed next update

**Comment by emberrolland** [comment]
That's great! Thanks for your help.
